import titanicS from "../images/titanicScene.png";
import tita from "../images/tit.png";
import movieLogo from "../images/movieLogo.png";
import spidey from "../images/spidey.png";
import jumanji from "../images/jumanji.png";
import wolf from "../images/wolf.png";
import mrs from "../images/mrs.png";
import hob from "../images/hob.png";
import spideyLogo from "../images/spideyLogo.png";
import spideyScene from "../images/spideyScene.png";
import moralis from "../images/moralis.png";
import moralisLogo from "../images/moralisLogo.png";
import moralisScene from "../images/moralisScene.png";
import jam from "../images/jam.png";
import jamLogo from "../images/jamLogo.png";
import jamScene from "../images/jamScene.png";
import bayw from "../images/bayw.png";
import shrek from "../images/shrek.png";
import lucy from "../images/lucy.png";
import topgu from "../images/topgu.png";
import imit from "../images/imit.png";
import reven from "../images/reven.png";
import tomb from "../images/tomb.png";
import amaz from "../images/amaz.png";
import bigs from "../images/bigs.png";
import secona from "../images/secona.png";
import ted from "../images/ted.png";
import amerp from "../images/amerp.png";

export const movies = [
  {
    Movie: "https://kroniclabz.mypinata.cloud/ipfs/QmTzVFvk3CfYyxWtPHJCZhLtxGdp9S2YBL5mfiiK9pY2up",
    Thumnbnail: tita,
    Scene: titanicS,
    Logo: movieLogo,
    Name: "Titanic",
    Description:
      "Staring Kate Winslet and Leonardo DiCaprio. Boy meets girl. Boy falls in love with girl. Ship hits an assberg, water rushes in, ship sinks. Boy died cause girl wouldnt move her ass over and share the door.",
    Genre: "Romance, Drama",
    Actors: "Kate Winslet, Leonardo DiCaprio",
    Year: "1998",
    Duration: "3h 14min",
  },
  {
    Movie: "https://ipfs.moralis.io:2053/ipfs/QmQJGEH1PsPAf8Mq6LGoJZ5Q3iJLqgCntAEmjAMatRVMeM/media/0",
    Thumnbnail: spidey,
    Scene: spideyScene,
    Logo: spideyLogo,
    Name: "Spiderman Homecoming",
    Description: "Peter Parker tries to stop the Vulture from selling weapons made with advanced Chitauri technology while trying to balance his life as an ordinary high school student.",
    Genre: "Action, Superhero, Comedy",
    Actors: "Tom Holland, Zendeya",
    Year: "2017",
    Duration: "2h 13min",
  },
  {
    Movie: "",
    Thumnbnail: jumanji,
    Scene: "",
    Logo: "",
    Name: "Jumanji",
    Description: "",
    Genre: "",
    Actors: "",
    Year: "",
    Duration: "",
  },
  {
    Movie: "https://bafybeifdflvepqrpncakeuya7lomonthommt2zzevnycmne2xnh3zsj34y.ipfs.nftstorage.link/",
    Thumnbnail: moralis,
    Scene: moralisScene,
    Logo: moralisLogo,
    Name: "Moralis Rap",
    Description: "Moralis serverless Web3 Dapps, is a beautiful music video that tells a touching story of how anyone can become a Web3 developer if they put their trust in the hands of the musically gifted team at Moralis. ",
    Genre: "Music Video",
    Actors: "Ivan Liljeqvist, Filip Martinsson, CTO Larsson",
    Year: "2021",
    Duration: "1min 2sec",
  },
  {
    Movie: "",
    Thumnbnail: wolf,
    Scene: "",
    Logo: "",
    Name: "Wolf Of Wallstreet",
    Description: "",
    Genre: "",
    Actors: "",
    Year: "",
    Duration: "",
  },
  {
    Movie: "",
    Thumnbnail: mrs,
    Scene: "",
    Logo: "",
    Name: "Mr and Mrs Smith",
    Description: "",
    Genre: "",
    Actors: "",
    Year: "",
    Duration: "",
  },
  {
    Movie: "https://ipfs.moralis.io:2053/ipfs/QmQJGEH1PsPAf8Mq6LGoJZ5Q3iJLqgCntAEmjAMatRVMeM/media/0",
    Thumnbnail: jam,
    Scene: jamScene,
    Logo: jamLogo,
    Name: "Jam Doughnut",
    Description: "In this masterpiece a wild Jay, endulges in flavorful jam doughnut. Be warned, this video is most certainly going to leave you craving for some sweets.",
    Genre: "Silent Mukbang",
    Actors: "Jay",
    Year: "2022",
    Duration: "1min 5sec",
  },
  {
    Movie: "",
    Thumnbnail: hob,
    Scene: "",
    Logo: "",
    Name: "Hobbit",
    Description: "",
    Genre: "",
    Actors: "",
    Year: "",
    Duration: "",
  },
  {
    Movie: "",
    Thumnbnail: shrek,
    Scene: "",
    Logo: "",
    Name: "",
    Description: "",
    Genre: "",
    Actors: "",
    Year: "",
    Duration: "",
  },
  {
    Movie: "",
    Thumnbnail: reven,
    Scene: "",
    Logo: "",
    Name: "",
    Description: "",
    Genre: "",
    Actors: "",
    Year: "",
    Duration: "",
  },
  {
    Movie: "",
    Thumnbnail: imit,
    Scene: "",
    Logo: "",
    Name: "",
    Description: "",
    Genre: "",
    Actors: "",
    Year: "",
    Duration: "",
  },
  {
    Movie: "",
    Thumnbnail: topgu,
    Scene: "",
    Logo: "",
    Name: "",
    Description: "",
    Genre: "",
    Actors: "",
    Year: "",
    Duration: "",
  },
  {
    Movie: "",
    Thumnbnail: lucy,
    Scene: "",
    Logo: "",
    Name: "",
    Description: "",
    Genre: "",
    Actors: "",
    Year: "",
    Duration: "",
  },
  {
    Movie: "",
    Thumnbnail: bayw,
    Scene: "",
    Logo: "",
    Name: "",
    Description: "",
    Genre: "",
    Actors: "",
    Year: "",
    Duration: "",
  },
  {
    Movie: "",
    Thumnbnail: tomb,
    Scene: "",
    Logo: "",
    Name: "",
    Description: "",
    Genre: "",
    Actors: "",
    Year: "",
    Duration: "",
  },
  {
    Movie: "",
    Thumnbnail: amaz,
    Scene: "",
    Logo: "",
    Name: "",
    Description: "",
    Genre: "",
    Actors: "",
    Year: "",
    Duration: "",
  },
  {
    Movie: "",
    Thumnbnail: bigs,
    Scene: "",
    Logo: "",
    Name: "",
    Description: "",
    Genre: "",
    Actors: "",
    Year: "",
    Duration: "",
  },
  {
    Movie: "",
    Thumnbnail: secona,
    Scene: "",
    Logo: "",
    Name: "",
    Description: "",
    Genre: "",
    Actors: "",
    Year: "",
    Duration: "",
  },
  {
    Movie: "",
    Thumnbnail: ted,
    Scene: "",
    Logo: "",
    Name: "",
    Description: "",
    Genre: "",
    Actors: "",
    Year: "",
    Duration: "",
  },
  {
    Movie: "",
    Thumnbnail: amerp,
    Scene: "",
    Logo: "",
    Name: "",
    Description: "",
    Genre: "",
    Actors: "",
    Year: "",
    Duration: "",
  },
];
